alternate: Maojinjuan

menu:
  部落格: /archives/ || list-alt
  關於我: /about/ || userhexo s

sidebar:
  avatar: "Penguin.png"

footer:
  powered: false

reward:
  enable: false

audio:
  - title: 列表1
    list:
    - https://music.163.com/#/playlist?id=2943811283
    - https://music.163.com/#/playlist?id=2297706586